### ISSUE TITLE
Password changing - verification/confirmation token

### ISSUE THREAD

**Issue by m-pilarczyk** [adshares/adpanel#144]
<a href="https://github.com/arturdebski"><img src="https://avatars2.githubusercontent.com/u/21009672?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arturdebski](https://github.com/arturdebski)**
_Thursday May 10, 2018 at 12:27 GMT_
_Originally opened as https://github.com/adshares/adserver-frontend/issues/140_

----

Changing password is instant. [Your email was changed successfully.]
We should add password_confirmation_function. (phone token, captcha or old password verification)

Also validation:
> Limit 
   failed_login_attempts x
   password_lock_time x
   password_life_time x
   password_grace_time x
   password_reuse_max x
   password_reuse_time x

**Comment by michaldzwigala** [comment]
- [ ] failed login attempts x - Fail
- [ ] password lock time x - Fail
- [ ] password life time x - Fail
- [ ] password grace time x - Fail
- [ ] password reuse max x - Fail
- [ ] password reuse time x - Fail

**Comment by yodahack** [comment]
okay, need to discuss tomorrow - what are the requirements on the password maintenance
