### ISSUE TITLE
Connect to Laravel API

### ISSUE THREAD

**Issue by m-pilarczyk** [adshares/adpanel#153]
<a href="https://github.com/m-pilarczyk"><img src="https://avatars3.githubusercontent.com/u/10977239?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [m-pilarczyk](https://github.com/m-pilarczyk)**
_Friday May 11, 2018 at 07:06 GMT_
_Originally opened as https://github.com/adshares/adserver-frontend/issues/149_

----

**Comment by yodahack** [comment]
to general
