### ISSUE TITLE
ADVERTISER: creating ads - no possibility to delete an image

### ISSUE THREAD

**Issue by proszeprosze** [adshares/adpanel#180]
steps:
-> login as advertiser
-> create campaign
-> create ads
-> upload an image

user can't delete or change uploaded image

**Comment by yodahack** [comment]
lets discuss @michaldzwigala

**Comment by michaldzwigala** [comment]
steps:
- [ ]  login as advertiser - Pass
- [ ] create campaign - Fail
- [ ] create ads - Fail
- [ ] upload an image
- [ ] user can't delete or change uploaded image
