### ISSUE TITLE
Buttons: Deposit Funds and Withdraw Funds have different width

### ISSUE THREAD

**Issue by proszeprosze** [adshares/adpanel#183]
Buttons Deposit Funds and Withdraw Funds have different width, witch is visible when user use low resolution devices.

Please check screens:

![gs5 a](https://user-images.githubusercontent.com/39900375/41041484-77b4b472-699f-11e8-8d0f-27d88caf8d99.JPG)
![gs5](https://user-images.githubusercontent.com/39900375/41041485-77d75996-699f-11e8-8d77-80d17364efe7.JPG)

**Comment by yodahack** [comment]
this is not a bug - it is just an improvement

bug - stuff does not work as it should, logic fails, feature is unavailable (might be styling but it means that user can not use it properly)
