### ISSUE TITLE
Logic fix - authentication 

### ISSUE THREAD

**Issue by KamilAdshare** [adshares/adpanel#212]
Currenty: 
 * first redirect then display account choice
 * user can ignore this feauture by clicking outside of the box
 * closing tab kill session
 * does not remember selection when loggin again
 * remember doesn't work

Expectation:
 * first account choice then redirect to proper dashboard
 * use shouldn't ignored type selection interface
 * closing tab shouldn't kill the session 
 * remember should work

Questions:
 * should closing browser process kill the session
 * should remember selection when log in again

**Comment by yodahack** [comment]
@michaldzwigala  bugs in this area may impact session behaviour, lets discuss proper application authentication behaviour

**Comment by michaldzwigala** [comment]
- [ ] should closing browser process kill the session
- [ ] log out >> log in - not work

**Comment by yodahack** [comment]
extracted #250 rest fixed
