### ISSUE TITLE
LOGIN: Registration of an incorrect email aa@aa

### ISSUE THREAD

**Issue by michaldzwigala** [adshares/adpanel#215]
Registration of an incorrect email aa@aa

![login](https://user-images.githubusercontent.com/39089871/42377159-5fef2530-8122-11e8-91ce-f95123492a8a.jpg)

**Comment by michaldzwigala** [comment]
![login](https://user-images.githubusercontent.com/39089871/42376903-2b497994-8121-11e8-83fc-a032702ef760.jpg)

**Comment by yodahack** [comment]
this is a proper email
