### ISSUE TITLE
Problem z logowaniem na 

### ISSUE THREAD

**Issue by michaldzwigala** [adshares/adpanel#226]
Problem z logowaniem na user@e11.click, strona przestała odpowiadać i zatrzymuje sie na zakładce logowania.

`{"id":1,"uuid":"0db7d309efff4a7783cdee5a2253303e","email":"user@e11.click","createdAt":"2018-07-12 06:50:13","updatedAt":"2018-07-12 06:50:20","deletedAt":null,"emailConfirmedAt":null,"name":null,"isAdvertiser":0,"isPublisher":1,"isAdmin":0,"isEmailConfirmed":false,"adserverWallet":{"createdAt":"2018-07-12 06:50:13","updatedAt":"2018-07-12 06:50:13","adsharesAddress":null,"paymentMemo":"User 0db7d309efff4a7783cdee5a2253303e","totalFunds":"0.000000000","totalFundsInCurrency":"0.00","totalFundsChange":"0.000000000","lastPaymentAt":null}}`

**Comment by yodahack** [comment]
still some bugs but at least one can log in more or less properly
